# products with Variants yml
# global categories
categories:
  - Phones
  - Cars
  - Laptops
  - Extra Category

#Phones:
products:
  - name: iPhone
    categories:
      - Phones
      - Extra Category
    attributes:
      - color
      - size
    options:
      size:
        - 32G
        - 64G
      color:
        - red
        - white
    variants:
      - name: iPhone Red 32G
        sku: iphone-32G-RED
        price: 3232
        stock: 10
      - name: iPhone Red 64G
        sku: iphone-64G-RED
        price: 3232
        stock: 20
      - name: iPhone White 32G
        sku: iphone-32G-WHITHE
        price: 3232
        stock: 30
      - name: iPhone White 64G
        sku: iphone-64G-WHITE
        price: 3232
        stock: 10

  - name: Galaxy
    attributes:
      - color
      - size
    options:
      size:
        - 32G
        - 64G
      color:
        - red
        - white
    variants:
      - name: Galaxy Red 32G
        sku: galaxy-32G-RED
        price: 3232
      - name: Galaxy Red 64G
        sku: galaxy-64G-RED
        price: 3232
      - name: Galaxy White 32G
        sku: galaxy-32G-WHITHE
        price: 3232
      - name: Galaxy White 64G
        sku: galaxy-56G-WHITE
        price: 3232

  - name: Motorola
    attributes:
      - color
      - size
    options:
      size:
        - 32G
        - 64G
      color:
        - red
        - white
    variants:
      - name: Motorola Red 32G
        sku: motorola-32G-RED
        price: 3232
      - name: Motorola Red 64G
        sku: motorola-64G-RED
        price: 3232
      - name: Motorola White 32G
        sku: motorola-32G-WHITHE
        price: 3232
      - name: Motorola White 64G
        sku: motorola-64G-WHITE
        price: 3232

#Cars:
  - name: Civic
    attributes:
      - motor
      - color
    options:
      motor:
        - 1.5 turbo
        - 2.0 turbo
      color:
        - red
        - white
    variants:
      - name: Civic 1.5 Red
        sku: civic-1.5-RED
        price: 100000
      - name: Civic 1.5 White
        sku: civic-1.5-WHITE
        price: 100000
      - name: Civic 2.0 Red
        sku: civic-2.0-RED
        price: 100000
      - name: Civic 2.0 White
        sku: civic-2.0-WHITE
        price: 100000

  - name: Mazda
    attributes:
      - motor
      - color
    options:
      motor:
        - 1.5 turbo
        - 2.0 turbo
      color:
        - red
        - white
    variants:
      - name: Mazda 1.5 Red
        sku: mazda-1.5-RED
        price: 100000
      - name: Mazda 1.5 White
        sku: mazda-1.5-WHITE
        price: 100000
      - name: Mazda 2.0 Red
        sku: mazda-2.0-RED
        price: 100000
      - name: Mazda 2.0 White
        sku: mazda-2.0-WHITE
        price: 100000

  - name: Corolla
    attributes:
      - motor
      - color
    options:
      motor:
        - 1.5 turbo
        - 2.0 turbo
      color:
        - red
        - white
    variants:
      - name: Corolla 1.5 Red
        sku: corolla-1.5-RED
        price: 100000
      - name: Corolla 1.5 White
        sku: corolla-1.5-WHITE
        price: 100000
      - name: Corolla 2.0 Red
        sku: corolla-2.0-RED
        price: 100000
      - name: Corolla 2.0 White
        sku: corolla-2.0-WHITE
        price: 100000

#Laptops:
  - name: Macbook Pro
    attributes:
      - color
      - size
    options:
      size:
        - 13"
        - 16"
      color:
        - space
        - white
    variants:
      - name: Macbook Pro 13 - "Space"
        sku: macbookpro-13"-SPACE
        price: 7898
      - name: Macbook Pro 16 - "Space"
        sku: macbookpro-16"-SPACE
        price: 7898
      - name: Macbook Pro 13 - "White"
        sku: macbookpro-13"-WHITE
        price: 7898
      - name: Macbook Pro 16 - "White"
        sku: macbookpro-"-WHITE
        price: 7898

  - name: Macbook Air
    attributes:
      - color
      - size
    options:
      size:
        - 13"
        - 16"
      color:
        - space
        - white
    variants:
      - name: Macbook Air 13 - "Space"
        sku: macbookair-13"-SPACE
        price: 7898
      - name: Macbook Air 16 - "Space"
        sku: macbookair-16"-SPACE
        price: 7898
      - name: Macbook Air 13 - "White"
        sku: macbookair-13"-WHITE
        price: 7898
      - name: Macbook Air 16 - "White"
        sku: macbookair-16"-WHITE
        price: 7898

  - name: Lenovo
    attributes:
      - color
      - size
    options:
      size:
        - 13"
        - 16"
      color:
        - Gray
        - white
    variants:
      - name: Lenovo 13 - "Gray"
        sku: lenovo-13"-GRAY
        price: 9999
      - name: Lenovo 16 - "GRAY"
        sku: lenovo-16"-GRAY
        price: 9999
      - name: Lenovo Space 13 - "White"
        sku: lenovo-13"-WHITE
        price: 9999
      - name: Lenovo 16 - "White"
        sku: lenovo-16"-WHITE
        price: 9999
