# products with Variants yml

#Phones:
products:
  - name: iPhone
    attributes:
      - color
      - size
    options:
      size:
        - 32G
        - 64G
      color:
        - red
        - white
    variants:
      - name: iPhone Red 32G
        sku: 32G-RED
        price: 3232
      - name: iPhone Red 64G
        sku: 64G-RED
        price: 3232
      - name: iPhone White 32G
        sku: 32G-WHITHE
        price: 3232
      - name: iPhone White 64G
        sku: 56G-WHITE
        price: 3232

  - name: Galaxy
    attributes:
      - color
      - size
    options:
      size:
        - 32G
        - 64G
      color:
        - red
        - white
    variants:
      - name: Galaxy Red 32G
        sku: 32G-RED
        price: 3232
      - name: Galaxy Red 64G
        sku: 64G-RED
        price: 3232
      - name: Galaxy White 32G
        sku: 32G-WHITHE
        price: 3232
      - name: Galaxy White 64G
        sku: 56G-WHITE
        price: 3232

  - name: Motorola
    attributes:
      - color
      - size
    options:
      size:
        - 32G
        - 64G
      color:
        - red
        - white
    variants:
      - name: Motorola Red 32G
        sku: 32G-RED
        price: 3232
      - name: Motorola Red 64G
        sku: 64G-RED
        price: 3232
      - name: Motorola White 32G
        sku: 32G-WHITHE
        price: 3232
      - name: Motorola White 64G
        sku: 56G-WHITE
        price: 3232

#Cars:
  - name: Civic
    attributes:
      - motor
      - color
    options:
      motor:
        - 1.5 turbo
        - 2.0 turbo
      color:
        - red
        - white
    variants:
      - name: Civic 1.5 Red
        sku: 1.5-RED
        price: 100000
      - name: Civic 1.5 White
        sku: 1.5-WHITE
        price: 100000
      - name: Civic 2.0 Red
        sku: 2.0-RED
        price: 100000
      - name: Civic 2.0 White
        sku: 2.0-WHITE
        price: 100000

  - name: Mazda
    attributes:
      - motor
      - color
    options:
      motor:
        - 1.5 turbo
        - 2.0 turbo
      color:
        - red
        - white
    variants:
      - name: Mazda 1.5 Red
        sku: 1.5-RED
        price: 100000
      - name: Mazda 1.5 White
        sku: 1.5-WHITE
        price: 100000
      - name: Mazda 2.0 Red
        sku: 2.0-RED
        price: 100000
      - name: Mazda 2.0 White
        sku: 2.0-WHITE
        price: 100000

  - name: Corolla
    attributes:
      - motor
      - color
    options:
      motor:
        - 1.5 turbo
        - 2.0 turbo
      color:
        - red
        - white
    variants:
      - name: Corolla 1.5 Red
        sku: 1.5-RED
        price: 100000
      - name: Corolla 1.5 White
        sku: 1.5-WHITE
        price: 100000
      - name: Corolla 2.0 Red
        sku: 2.0-RED
        price: 100000
      - name: Corolla 2.0 White
        sku: 2.0-WHITE
        price: 100000

#Laptops:
  - name: Macbook Pro
    attributes:
      - color
      - size
    options:
      size:
        - 13"
        - 16"
      color:
        - space
        - white
    variants:
      - name: Macbook Pro 13 - "Space"
        sku: PRO-13"-SPACE
        price: 7898
      - name: Macbook Pro 16 - "Space"
        sku: PRO-16"-SPACE
        price: 7898
      - name: Macbook Pro 13 - "White"
        sku: PRO-13"-WHITE
        price: 7898
      - name: Macbook Pro 16 - "White"
        sku: PRO-16"-WHITE
        price: 7898

  - name: Macbook Air
    attributes:
      - color
      - size
    options:
      size:
        - 13"
        - 16"
      color:
        - space
        - white
    variants:
      - name: Macbook Air 13 - "Space"
        sku: PRO-13"-SPACE
        price: 7898
      - name: Macbook Air 16 - "Space"
        sku: PRO-16"-SPACE
        price: 7898
      - name: Macbook Air 13 - "White"
        sku: PRO-13"-WHITE
        price: 7898
      - name: Macbook Air 16 - "White"
        sku: PRO-16"-WHITE
        price: 7898

  - name: Lenovo
    attributes:
      - color
      - size
    options:
      size:
        - 13"
        - 16"
      color:
        - Gray
        - white
    variants:
      - name: Lenovo 13 - "Gray"
        sku: PRO-13"-GRAY
        price: 9999
      - name: Lenovo 16 - "GRAY"
        sku: PRO-16"-GRAY
        price: 9999
      - name: Lenovo Space 13 - "White"
        sku: PRO-13"-WHITE
        price: 9999
      - name: Lenovo 16 - "White"
        sku: PRO-16"-WHITE
        price: 9999
