# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
# https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html

#-- https://docs.clover.com/reference#inventorygetitems-1
# https://docs.clover.com/docs/managing-items-item-groups

@prod_base = api.clover.com
@dev_base = apisandbox.dev.clover.com
@token = {{$dotenv CL_TOKEN}}
@cl_merchant_id = {{$dotenv CL_MERCHANT_ID}}
@base_url = https://{{dev_base}}/v3/merchants/{{cl_merchant_id}}

### merchant -------------------------------------------------------------------
GET {{base_url}}
Content-Type: application/json
Authorization: Bearer {{token}}

# Categories -------------------------------------------------------------------
### get all
GET {{base_url}}/categories
    ?limit=4
    &offset=8
Content-Type: application/json
Authorization: Bearer {{token}}

### create
POST {{base_url}}/categories
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "new category"
}

### delete
DELETE  {{base_url}}/categories/7R79TGAP8BVHT
Content-Type: application/json
Authorization: Bearer {{token}}

### Associating items with a category
POST {{base_url}}/category_items
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "elements": [
    { "category": { "id": "W055X40CFZNVW" }, "item": { "id": "ST7YBQVMT1HFA" } },
    { "category": { "id": "W055X40CFZNVW" }, "item": { "id": "GMB9EQY31HGB8" } }
  ]
}

### Deleting item associations
POST {{base_url}}/category_items
     ?delete=true
Content-Type: application/json
Authorization: Bearer {{token}}

{ "elements": [{"category":{"id":"categoryId"},"item":{"id":"itemId"}}] }

# Item Groups ------------------------------------------------------------------
### get all
GET {{base_url}}/item_groups
    ?expand=items,attributes
Content-Type: application/json
Authorization: Bearer {{token}}

### new
POST {{base_url}}/item_groups
Content-Type: application/json
Authorization: Bearer {{token}}

// does not work to send items here, needs to be added
// when creating an item
{
    "name": "iPad Pro"
}

# Attributes  ------------------------------------------------------------------
### get all
GET {{base_url}}/attributes
    ?expand=options,menu_items
Content-Type: application/json
Authorization: Bearer {{token}}

### create
POST {{base_url}}/attributes?expand=options
Content-Type: application/json
Authorization: Bearer {{token}}

// name and itemGroup required
{
  "name": "Color",
  "itemGroup": {
    "id": "VWWJPBKJ3K5M4"
  }
}

# Options  ---------------------------------------------------------------------
### get all
GET {{base_url}}/options
Content-Type: application/json
Authorization: Bearer {{token}}

### create
@attribute_id = PBJZ99TYPFZRE
POST {{base_url}}/attributes/{{attribute_id}}/options
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "128G"
}

# Items (Products) -------------------------------------------------------------
### get all | modifiedTime = date +%s
GET {{base_url}}/items
    ?expand=categories,itemStock,options
    &return_null_fields=true
    &filter=modifiedTime>=1614120207
Content-Type: application/json
Authorization: Bearer {{token}}

### new
POST {{base_url}}/items
Content-Type: application/json
Authorization: Bearer {{token}}

// only name and price are required
{
    "hidden": false,
    "itemGroup": {
        "id": "NZV186DJ2W64T"
    },
    "defaultTaxRates": true,
    "isRevenue": true,
    "name": "iphone?????",
    "code": "IPHONE",
    "sku": "IPHONE",
    "price": 29999,
    "priceType": "FIXED",
    "unitName": "item"
}

### edit
PUT {{base_url}}/items/HC28W9N9Y1SFG
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "itemStock": {
        "quantity": 99
    },
    "name": "MacBook Air",
    "code": "AIR1",
    "sku": "AIR1-1",
    "price": 9999
}

### delete ?itemIds=[itemId],[itemId],[itemId]
DELETE {{base_url}}/items?itemIds=

### modify multiple items
# post create
# put updates
POST {{base_url}}/bulk_items
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "items": [
    { "name": "new", "price": 999, "itemGroup": {"id": "VWWJPBKJ3K5M4"} },
    { "name": "new", "price": 999, "itemGroup": {"id": "VWWJPBKJ3K5M4"} }
  ]
}

# item/option ------------------------------------------------------------------
### create asociation
POST {{base_url}}/option_items
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "elements": [
    { "option": { "id": "3XPR9F347ZDX6" }, "item": { "id": "0CTS789TGWY7M" } },
    { "option": { "id": "9C71JB22RRRMG" }, "item": { "id": "YN2TBXKQACE76" } },
    { "option": { "id": "VBEPH4KQGFN54" }, "item": { "id": "9GG9MJEJJ5E8Y" } },
    { "option": { "id": "A7D6ZGBE1K7ZW" }, "item": { "id": "MSB34F4KABK7C" } }
  ]
}

# Inventory Levels -------------------------------------------------------------
### get all
GET {{base_url}}/item_stocks
Content-Type: application/json
Authorization: Bearer {{token}}

### update single
POST {{base_url}}/item_stocks/HC28W9N9Y1SFG
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "quantity": 99.0
}

# Orders -----------------------------------------------------------------------
### get
GET {{base_url}}/orders?expand=discounts,payments
Content-Type: application/json
Authorization: Bearer {{token}}

### create
POST {{base_url}}/atomic_order/orders
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "orderCart" : {
    "title": "my order",
    "currency": "USD",
    "paymentState": "OPEN",
          "state": "open",
      "manualTransaction": false,
    "lineItems": [
      { "item": { "id": "JKCM679Q57TE6" } }
    ],
    "orderType" : {
      "taxable" : false,
      "isDefault" : false,
      "filterCategories" : false,
      "isHidden" : false,
      "isDeleted" : false
    },
    "groupLineItems" : false
  }
}
